### ISSUE TITLE
the robustness of "implies" operation

### ISSUE THREAD

**Issue by xiaoyaooo** [nickovic/rtamt#71] opened 2021-03-08 12:34 UTC
Hi Dear authors,
I was trying to use the implies operator in specifications and have noticed a confusing case.

for example, I have two sets of data of a = [2, 2] and b = [0, -1] for timestep = 0 and 1,
and the specification is "(a==2) implies (b >= 0)"

from these three formulas below, 
rho(phi == psi,w,t) = -|rho(phi,w,t) - rho(psi,w,t)|
rho(phi >= psi,w,t) = rho(phi,w,t) - rho(psi,w,t)
rho(phi -> psi,w,t) = max(-rho(phi,w,t),rho(psi,w,t))

the results are 
from the first two formulas, 
rho(a==2) = [-|2-2|, -|2-2|] = [0, 0] for time steps 0 and 1 
rho(b>=0) = [0-0, -1-0] = [0, -1] for time steps 0 and 1

from the second rho(phi -> psi,w,t) formula,  
the results rho((a==2) implies (b >= 0)) = [max(-0, 0), max(-0, -1)] = [0, 0] for timesteps 0 and 1.
and that means the results are the same for those two datasets.

However, the specification "(a == 2) implies (b >= 0)" is satisfied when a = 2 and b = 0
but violated when a = 2 and b = -1, which is not what we have seen from the rho((a==2) implies (b >= 0)) result.

Is this still a normal case and I've understood something wrong, or is this a special one and needs to be particularly taken care of?

Thank you very much in advance!

**Comment by nickovic** [comment] 2021-03-08 23:27
Hello,

This is the expected behavior for the quantitative semantics of STL. 

When defining qualitative semantics, we use the satisfaction relation (w,t) \models phi. When defining quantitative semantics, we use the robustness degree rho(phi, w, t). The satisfaction relation and the robustness degree are related via the following soundness theorem:

if rho(phi, w, t) > 0 then (w,t) \models phi, and
if rho(phi, w, t) < 0 then (w,t) \not \models phi

Note that this theorem says nothing about the case when rho(phi, w, t) = 0. That is because any arbitrary small perturbation in w results in the overall formula switching its (qualitative) satisfaction/violation status.

In quantitative semantics, a predicate (a == 2) is supported but is not robust, i.e. it always yields robustness 0. When you say 
rho((a==2) implies (b >= 0))
with a = 2 and b = -1, the overall robustness of the formula will be dominated by the fact that in the quantitative semantics a ==  2 is "barely satisfied" (with robustness 0). 

The overall robustness basically tells you how far is w from satisfying the formula. Your intuition tells you that the value should be -1 because b >= 0 is violated by 1. However, in order to satisfy the formula, we can do better - it suffices to change the value of the variable a by an arbitrarily small amount that you can make as close as you wish to 0, and in that case the left hand side of the implication (a == 0) becomes false, and the overall formula is trivially satisfied.

Final note - you may want to look at out interface-aware semantics (supported by RTAMT). It allows you to define a as an input, and b as an output. If you compute the output robustness, then the predicate (a == 0) is interpreted as a Boolean predicate -- it has value +inf if a = 0, and value -inf if a != 0. This means that one cannot play anymore the trick from the previous paragraph, and change a by a small amount to get phi satisfied. Under that semantic interpretation, the output b dominates the robustness computation and rho(phi, w, t) = -1, following your original intuition.

**Comment by xiaoyaooo** [comment] 2021-03-09 10:59
Hi @nickovic 
Thank you very much for your very detailed explanation!
I will definitely have a look at your IA semantics!

**Comment by xiaoyaooo** [comment] 2021-03-09 12:06
Hey @nickovic ,
Hello, I've just tried your IA semantics, with setting semantics=rtamt.Semantics.OUTPUT_ROBUSTNESS
the result looks pretty good when I have spec like "(var1>2) -> (var2>0)" with real input either bigger or smaller than 2.
However, when var1 actually equals 2, then the output robustness is "nan", this also happens if I define a spec like "(var1==2) -> (var2>0)"
Basically, as long as the real input var1 equals the value in the predicate, no matter which operator I used ">",">=" or "==", the output robustness will be nan.
Do you have any idea why this happened?
Thanks in advance!

**Comment by xiaoyaooo** [comment] 2021-03-09 12:14
the program I used for testing is the example here, in the 70-IA-semantics branch
"examples\features\ia-semantics\ia_stl_discrete_time_offline_python.py"

and I have changed the spec in the second block "# # OUTPUT ROBUSTNESS"
to spec.spec = '(x>0.3) -> (y>=1.25)' / spec.spec = '(x==0.3) -> (y>=1.25)' / spec.spec = '(x>=0.3) -> (y>=1.25)'
according to the dataSet, at time step 2, x=0.3 and y=1.3, so all of these three specs should be satisfied. But the robustnesses are all "nan"

**Comment by nickovic** [comment] 2021-03-10 09:22
Thanks for your feedback. 

Let me explain why "nan" happens. When computing output robustness, the input predicates shall either have the value +inf (if the predicate is satisfied) or -inf (if the predicate is violated).

The current implementation does this by taking the standard robustness of the predicate on inputs and multiplying it with inf. This works correctly, except when the standard robustness of the predicate equals to 0. In that case, we multiply 0 by inf, giving us "nan".

This is a bug.

To fix it, we need to distinguish whether the predicate with robustness 0 is satisfied or violated according to the qualitative semantics, and assign to it output robustness of +inf or -inf accordingly.

For instance, consider predicates phi1 = x >= 0 and phi2 = x > 0 and x=0, where x is an input variable. Currently, both phi1 and phi2 are evaluated to "nan". The desired evaluation is +inf for phi1 (because the valuation of x satisfies the predicate) and -inf (because the valuation of x violates the predicate).

I keep this issue open and will fix the implementation.

**Comment by xiaoyaooo** [comment] 2021-03-10 09:39
Hi @nickovic ,
Thank you very much for your explanation! : )

**Comment by nickovic** [comment] 2021-03-11 22:30
The issue is fixed.

**Closed by nickovic** 2021-03-11 22:30 UTC
Labels: bug
